### ISSUE TITLE
require() of ES modules is not supported.

### ISSUE THREAD

**Issue by rikwilbrink** [hperrin/smui-example-sveltekit#1]
Running the REPO results in this error:

Steps to reproduce:
1. Run windows
2. Clone
3. remove vite-workaround from prepare function (optionally try to remove *.js.map yourself from folder)
4. npm install
5. npm run dev

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\{path}\smui-example-sveltekit\node_modules\@smui\button\bare.js
require() of ES modules is not supported.
require() of C:\Users\{path}\smui-example-sveltekit\node_modules\@smui\button\bare.js from C:\Users\{path}\smui-example-sveltekit\node_modules\vite\dist\node\chunks\dep-5c642f9e.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename bare.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\{path}\smui-example-sveltekit\node_modules\@smui\button\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (C:\Users\{path}\smui-example-sveltekit\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:69047:17)
    at ssrImport (C:\Users\{path}\smui-example-sveltekit\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:69005:20)
    at eval (C:\Users\{path}\smui-example-sveltekit\src\routes\$layout.svelte:7:31)
    at instantiateModule (C:\Users\{path}\smui-example-sveltekit\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:69033:166)
```

**Comment by hperrin** [comment]
This is in Windows? Hmm. I don't have a Windows machine to test this on right now.

**Comment by rikwilbrink** [comment]
Based on your prepare function, I assume this solution is Mac bases.

But I doubt the issue is OS related

**Comment by Shogoki** [comment]
> Based on your prepare function, I assume this solution is Mac bases.
> 
> But I doubt the issue is OS related

Yes, the one here is relying on the `find`utility. 

I made a version using a node-script instead that should work for windows, too.
The PR #2 is still open. But if you want to try it you can take a look [here](https://github.com/Shogoki/smui-example-sveltekit/tree/vite-workaround/node-script).

**Comment by hperrin** [comment]
The Windows compatible script is in!

**Comment by abannsunny** [comment]
I am very new to Sveltekit and I was trying to add smui to my project.

There are a few changes to the project  that npm init svelte@next scaffolds from this example.

the svelte.config.cjs is now svelte.config.js

and the $layout.svelte is now __layout.svelte


```
{
  "name": "My-App",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --write --plugin-search-dir=. .",
    "prepare": "npm run vite-workaround && npm run smui-theme-light && npm run smui-theme-dark",
    "vite-workaround": "node _helper/vite-workaround.js",
    "smui-theme-light": "smui-theme compile static/smui.css -i src/theme",
    "smui-theme-dark": "smui-theme compile static/smui-dark.css -i src/theme/dark"
  },
  "devDependencies": {
    "@babel/core": "^7.14.2",
    "@material/theme": "^11.0.0",
    "@material/typography": "^11.0.0",
   
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "sass": "^1.32.13",
    "smui-theme": "^4.2.0",
    "svelte": "^3.38.2",
    "svelte-loader": "^3.1.1",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.2.2",
    "@lukeed/uuid": "^2.0.0",
    "@smui/button": "^4.2.0",
    "cookie": "^0.4.1",
  }
}
```

the error that I get right now is

[vite] Error when evaluating SSR module Path\src\routes\__layout.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: Path\node_modules\@smui\button\index.jsrequire() of ES modules is not supported.
require() of Path\node_modules\@smui\button\index.js from Path\node_modules\vite\dist\node\chunks\dep-efbff8d5.js is an ES module file as it is a .js file whose nearest parent package.json contains 
"type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from Path\node_modules\@smui\button\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (Path\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:68092:17)
    at ssrImport (Path\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:68045:20)
    at eval (Path\src\routes\__layout.svelte:7:31)
    at instantiateModule (Path\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:68078:166)       
Must use import to load ES Module: Path\node_modules\@smui\button\index.js
require() of ES modules is not supported.
require() of Path\node_modules\@smui\button\index.js from Path\node_modules\vite\dist\node\chunks\dep-efbff8d5.js is an ES module file as it is a .js file whose nearest parent package.json contains 
"type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from Path\node_modules\@smui\button\package.json.

**Comment by rikwilbrink** [comment]
in svelte.config, explicitly mention smui and material packages in the vite noExternal array.

**Comment by abannsunny** [comment]
The updated FAQ on sveltekit  says 

"Old beta versions of the SvelteKit template included the configuration value noExternal: Object.keys(pkg.dependencies || {}) in svelte.config.js. First, please check if this line is present in your project and remove it if so. Removing this line fixes most issues and has since been removed from the template."

The second most commonly-encountered issue is having a Svelte component that imports a CommonJS library. In this case, you should try to work with the library authors to distribute an ESM version of the dependency. However, in the meantime, you can workaround this issue by adding the dependency to vite.optimizeDeps.include in svelte.config.js.

https://kit.svelte.dev/faq#packages


I got the repo to start working I will create a PR later tonight
